name: flutter_termii
description: Flutter package that helps developers use messaging channels to verify and authenticate customer transactions.
version: 0.2.1
homepage: https://github.com/Oshinowo/flutter_termii
documentation: https://github.com/Oshinowo/flutter_termii

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
